name: Hackl0us-GeoIP2-CN-update
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 */12 * * *"
  
jobs:
  process-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Process IPs and save to ./rules/GeoIP2-CN.list
      run: |
        wget https://raw.githubusercontent.com/Hackl0us/GeoIP2-CN/release/CN-ip-cidr.txt -O GeoIP2-CN.txt
        sed -i '/^[0-9.]\+\/[0-9]\+$/!d' GeoIP2-CN.txt
        sed -i 's/^/IP-CIDR,/' GeoIP2-CN.txt
        sed -i 's/$/,no-resolve/' GeoIP2-CN.txt
        mkdir -p rules
        cp GeoIP2-CN.txt rules/GeoIP2-CN.list
      
    - name: Add changes to the repository
      run: |
        git add .
        git status

    - name: Commit and push changes
      run: |
        git commit -m "Update IP CIDR list" -a
        git push
    - name: Send email notifications
      if: ${{ failure() }}
      run: echo "Error occurred, but email notifications are ignored."
